.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoineuro_qt test_bitcoineuro_qt
clean: FORCE
	$(MAKE) -C .. bitcoineuro_qt_clean test_bitcoineuro_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoineuro_qt_check
bitcoineuro-qt bitcoineuro-qt.exe: FORCE
	 $(MAKE) -C .. bitcoineuro_qt
